### ISSUE TITLE
Non-blocking `git-fetch` replication

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#13]
Currently, `git-fetch` runs within the service thread, which means it blocks the service from processing other requests.

We want a worker-thread architecture where one worker is assigned to each project, and `fetch` jobs are sent to these threads. The service can then be woken up when the worker is done with the work.

*Implementation details*

* Use crossbeam-channel to communicate between threads
* Use the Reactor's `Waker` to wake-up the service, which will then read from its worker channel
* Having one channel per project is not a good idea, since we could have 10K+ projects
* Worker thread pool should be started up from `client` or `main`, and be handed a waker and client handle
* An external thread-pool dependency is probably overkill for this

**Comment by FintanH** [comment]
We used a `Pool<Storage>` for doing multi-threaded operations in `radicle-link` That functionality is available in [`git-storage`](https://github.com/radicle-dev/radicle-git/blob/main/git-storage/src/pool.rs) now.

**Comment by cloudhead** [comment]
Great, will take a look. We can't use it as-is due to it being async, but it's good inspiration.

**Comment by FintanH** [comment]
> Great, will take a look. We can't use it as-is due to it being async, but it's good inspiration.

Are you planning on writing all code as sync? :thinking:

**Comment by cloudhead** [comment]
> > Great, will take a look. We can't use it as-is due to it being async, but it's good inspiration.
> 
> Are you planning on writing all code as sync? thinking

Yes, since the alternative is writing all code as async (they don't really mix well)

**Comment by FintanH** [comment]
> > > Great, will take a look. We can't use it as-is due to it being async, but it's good inspiration.
> > 
> > 
> > Are you planning on writing all code as sync? thinking
> 
> Yes, since the alternative is writing all code as async (they don't really mix well)

Sweet, good to know!

**Comment by cloudhead** [comment]
My stance on async in rust is pretty firm: it's not worth it unless you need to handle 100K+ active connections.

**Comment by cloudhead** [comment]
Closed by #232
