### ISSUE TITLE
Multi-step git fetch

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#14]
Currently, we fetch all refs in one go and then verify them.

We should use a multi-step process where:
1. Identity branches for all remotes are fetched and verified
2. Signed refs are fetched and verified against the identity branches
3. All other refs are fetched and verified against the signed refs

**Comment by FintanH** [comment]
For :sparkles:inspiration:sparkles: `radicle-link` did this in `link-replication`, but it used `gitoxide` via `link-git` since it supported protocol v2.

**Comment by cloudhead** [comment]
Good to know, kind of annoying that we need to use gitoxide just for this :thinking: 
Using a sub-process is another way and we would be able to use the `--atomic` as well, hmm.
