### ISSUE TITLE
Check all lengths when decoding

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#16]
To prevent OOM errors, we should check all lengths in the `wire` protocol. Currently, lengths are capped to 16bits, but for certain types of data, that could still be a lot, eg. when sending over public keys or hashes.

**Comment by slack-coder** [comment]
The biggest offenders are messages containing vectors of addresses which can take up to 65525 * 256 bytes => 16-17 Mb.

As mentioned out of band, messages will be able to handle these sizes given support with frames.

There are two other problems to consider.

  - Large Announcement messages
    A single Announcment Message is multiplied as it is gossiped across the network.  Sending many large Announcement Messages (i.e. Node Announcements) could cause significant traffic.  With nodes having up to eight connected peers by default, one messages of 17 Mb could be up to 136 Mb for each node.

  - Exhausting of internal tables

    Emitting large amounts of Inventory Announcement will exhaust the routing table, and others pretty fast.  So in these cases, adding sane upper bounds on message vectors will help, and adding proof of work to Announcement Messages to make flooding the network costly.
