### ISSUE TITLE
Oid parsing should be stricter

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#166]
The OID is a number typically shown in hex, and is used as an ID for many types.  Parsing OID from strings should expect a set length, but current parsing incorrectly allows shorter strings.

Below is an example test documenting the problem.
```
#[test]
fn test_oid_parse() {
    let str = "17309938d4f6cd8ad6805a0561928f11b2df2000";
    let val = issue::IssueId::from_str(&str);
    assert!(val.is_ok(), "expect oid to be ok");
    assert_eq!(
        str,
        val.unwrap().to_string(),
        "string encoding should be consistent"
    );

    let short_str = "17309938d4f6cd8ad6805a0561928f11b2df2";
    let val = issue::IssueId::from_str(&short_str);
    assert!(val.is_err(), "expect shortened OID to be in error");
}
```

**Comment by cloudhead** [comment]
Hmm we just use `git2::Oid::from_str` internally. Can you confirm that this is a problem with `git2` as well?

I'm not sure this is a "problem" per se: Git doesn't prefix the sha-1 with `0`s, ie. a shorter hash would not be like `00123`, it would just be `123`. So I'm guessing this is intended behavior.

**Comment by FintanH** [comment]
It uses `libgit2` internally https://docs.rs/git2/0.15.0/src/git2/oid.rs.html#26-39

I think this is fine, it's just being "smart" :)

**Comment by slack-coder** [comment]
> Can you confirm that this is a problem with git2 as well?

git2 behaves the same way.

> I'm not sure this is a "problem" per se: Git doesn't pad the sha-1 with 0s, ie. a shorter hash would not be like 00123, it would just be 123. So I'm guessing this is intended behavior.

The OID's are treated in the inverse so '123' would become '123000...'.  I can only guess why it behaves this way, and I have a good one, but its unexpected behavior.

Treating checksum output like regular numbers by omitting leading 0's is strange.  Hex is used to display a length of bits because it aligns with power of two, removing leading 0's is omitting bit information.

> I think this is fine, it's just being "smart" :)

As long as we know about it.  These exceptions can build up to become a death by a thousand cuts.  Its annoying :/.

**Comment by FintanH** [comment]
What kind of problems do you foresee happening?

**Comment by slack-coder** [comment]
> What kind of problems do you foresee happening?

I'd rather build things simpler which I can better predict, than ones harder to predict with more exceptions.  Now OID's don't act like the checksums they look like.
