### ISSUE TITLE
radicle-httpd: Improve project listing load time and not include failed projects in pagination

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/heartwood#179]
The `project_root_handler` can be improved by:
- Collect project infos in parallel https://github.com/radicle-dev/radicle-client-services/commit/63a8dd919f3e7bad1d4fe4e075423bb9f022883d
- Change the iterator to not count failed projects https://github.com/radicle-dev/radicle-client-services/pull/206/commits/f4cf69e283992f4dc2395ac0781ddf58ec268e38

**Comment by cloudhead** [comment]
Have you tested it in heartwood?

**Comment by sebastinez** [comment]
Haven't had the chance to test it, saw that we didn't transfer the code we had in place or wanted to implement.
Wanted to bring the issue up more to not loose track of it.
Will close it if see that it has been resolved by Heartwood

**Comment by cloudhead** [comment]
Ok, heartwood should perform very differently, so let's see.

**Comment by cloudhead** [comment]
Can we close this?

**Comment by sebastinez** [comment]
I haven't seen any projects so far failing, so I think we can close it.
