### ISSUE TITLE
radicle::cob: Minor comment typo

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/heartwood#186]
We should replace `issue` with `patch`

here 
https://github.com/radicle-dev/heartwood/blob/0dc34dc15d596f2118b4eaa63949e8f41fc5c0a2/radicle/src/cob/patch.rs#L744
and here
https://github.com/radicle-dev/heartwood/blob/0dc34dc15d596f2118b4eaa63949e8f41fc5c0a2/radicle/src/cob/patch.rs#L749

**Comment by cloudhead** [comment]
Good catch, fixed in bf22cea
