### ISSUE TITLE
radicle-cli: Port `rad comment`

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/heartwood#187]
We should port `rad comment` from https://github.com/radicle-dev/radicle-cli/tree/master/comment

**Comment by slack-coder** [comment]
The `rad comment` command includes a `--reply-to` argument which defines the comment being replied to.  Comment ID's (OpIDs) have yet to have a String conversion.  How should it be supported?  Or should we work around it with `term::comment_select` as `rad issue` does?

Here's what an OpID looks like:
```
pub struct OpId(Lamport, ActorId);
```

**Comment by slack-coder** [comment]
We also need commenting support for `Patch` as has been done for `Issue`.

**Comment by slack-coder** [comment]
This is almost complete.

How do we want comments to be show?

**Comment by slack-coder** [comment]
@cloudhead this is complete
