### ISSUE TITLE
Support multiple signatures in identity branch commits

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#20]
To handle projects with multiple delegates, commits on the identity branch should support multiple `gpgsig` headers.

We have to be able to:
1. Encode/decode the ssh armored signature format
2. Add signature to a commit, before writing it to the ODB
3. Verify histories with multiple signatures

**Comment by cloudhead** [comment]
Related to #126

**Comment by FintanH** [comment]
This is done, right? Or what are we missing?

**Comment by cloudhead** [comment]
Yes, I think so... They are trailer signatures though, correct?

**Comment by FintanH** [comment]
Oh you're right. I'll take this on then and switch over to using `git-commit` :) I'll also fix up that issue we had in `git-commit` not checking the parent `Oid`s

**Comment by FintanH** [comment]
Oh wait, you're assigned 😅

**Comment by FintanH** [comment]
Aggregating commits over the blobs means we _should_ be able to add the signatures to the commit, right? Otherwise, we'd have a chicken and egg problem where we would need the commit but can't add the signatures :)

**Comment by cloudhead** [comment]
Ah but the thing is, `gpgsig` headers are supposed to be signatures over the commit hash, not the blob..

**Comment by cloudhead** [comment]
It is a subset :), It's the commit object minus any `gpgsig` header that is signed.

**Comment by FintanH** [comment]
Ok, so I guess the question then is, do we want to keep using trailers and sign the blobs or do we want to redesign signatures to figure out if we can use the gpgsigs instead? :)

**Comment by cloudhead** [comment]
I'd say trailers is fine... we have the code and it works. Unless you can think of a straightforward way of using headers..

**Comment by FintanH** [comment]
Ya, I'd agree and nothing that comes to mind immediately. It _might_ be possible since we're gathering signatures out-of-band anyway so we could probably predict the commit object.

Should we kick this out of the 1.0 milestone?

**Comment by cloudhead** [comment]
Yup!

**Comment by cloudhead** [comment]
Actually, we should close it no? It's mainly about multisignatures, not so much where those signatures are stored.

**Comment by FintanH** [comment]
Ya sounds good! Closed via https://github.com/radicle-dev/heartwood/pull/192
