### ISSUE TITLE
Commenting on a Patch's Review

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#244]
Should it be possible to reply to patch review comments?

A patch can be commented on in three places.  One is the patch's discussion thread, the other as a comment in Patch.Review, and a code comment in Patch.Review.

A Patch discussion supports replying to comments via the `Thread` type. The other two places lack the support, Review.inline and Review.comment.

```
/// A patch review on a revision.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct Review { 7 implementations
    /// Review verdict.
    pub verdict: LWWReg<Option<Verdict>>,
    /// Review general comment.
    pub comment: LWWReg<Option<Max<String>>>,
    /// Review inline code comments.
    pub inline: LWWSet<Max<CodeComment>>,
    /// Review timestamp.
    pub timestamp: Max<Timestamp>,
}
```

**Comment by cloudhead** [comment]
I'm not sure it's needed. For example, GitHub doesn't allow this and I've never felt it to be an issue. It's always possible to add a comment on the revision's discussion thread, quoting the review. But in terms of potential UIs, we want to limit the number of disjoint thread, as it'll become hard to navigate..

**Comment by FintanH** [comment]
> I'm not sure it's needed. For example, GitHub doesn't allow this and I've never felt it to be an issue. It's always possible to add a comment on the revision's discussion thread, quoting the review. But in terms of potential UIs, we want to limit the number of disjoint thread, as it'll become hard to navigate..

Sure it does, here's an [example](https://github.com/radicle-dev/rips/pull/1#pullrequestreview-1206685004) of a threaded discussion on an inline comment.

It doesn't allow replying to the kind of "top-level" review comment, but honestly, I'd prefer it if it did instead of having to quote a reply along the main thread. But maybe that's just a matter of personal taste.

**Comment by cloudhead** [comment]
Yeah, line comments sure, though that's already possible here by having >1 line comments.

Regarding top-level review comments, my concern is mainly around how we display all these "threads" in the UI. Not against it per se..

**Comment by gsaslis** [comment]
> A patch can be commented on in three places. One is the patch's discussion thread, the other as a comment in Patch.Review, and a code comment in Patch.Review.

The way I've been thinking about the separation is the following: 
* the main discussion is A discussion about the whole Patch Proposal 
  * read another way, this is a discussion about the full changeset proposed 
    * framed like this, it is obvious there can also be other discussions about smaller changesets (specific lines)

My main takeaway from the above is that _discussions_ are **always** about a specific changeset (even if that changeset is all of the lines in the Patch Proposal).   

In all of these discussions, I take "discussion" to mean:  a single discussion, i.e. no threads, as these typically are there to fork into _separate_ discussions. 

With that in mind, I don't see a need for _threads_ anywhere in this model. It's just separate discussions about specific changesets. 

Does that make sense / help ?

**Comment by FintanH** [comment]
> Yeah, line comments sure, though that's already possible here by having >1 line comments per line.

Sure, but would it not make sense to reuse `Thread` in this case?

**Comment by FintanH** [comment]
> the main discussion is A discussion about the whole Patch Proposal

In my opinion, I don't think that's a hard fact. I think the main topic of a discussion can spread into separate, but adjacent, topics. Look at how we're discussing the top-level discussion but I'm also discussing inline comments in parallel :)

**Comment by gsaslis** [comment]
"People will always hack the system". 😁 

I don't think this model would in any way prevent that... 

and yet I think this is a simpler model that also expresses intent: it reminds people of what the discussion is meant to accomplish (accept/reject patch proposal)

**Comment by slack-coder** [comment]
Hey guys, just pinging this topic to keep it moving.

My personal opinion is I agree with @gsaslis it would be simpler without reply-to support in these discussions.  Seeing how it works on github is likely what's persuading me.

With a single ordered list of comments, it can keep the discussion focused (as per what @gsaslis says?).  I can see Threaded discussions forking off from the main thread, but referencing similar topics, then it becomes more chaotic.

Its also simpler to add features then remove them.  Its safer to proceed without threaded patches and add them later when its evidently needed.

**Comment by cloudhead** [comment]
The thing is, right now there's no "review discussion" at all. Only one comment is allowed per review (besides inline comments).

So maybe we could change `comment` to `disucssion` inside `Review`.. This would allow reviews to be discussed. However as @slack-coder we may regret this decision and it'll be annoying to remove. I propose we close this thread, use patches, and decide whether or not we need it after using it for a while.

**Comment by cloudhead** [comment]
So, patches don't have discussions, *revisions* do. But effectively, patches always have at least one revision.
Inline comments aren't discussions, but you can have multiple inline comments on the same line of code, which can be displayed as a discussion.

**Comment by gsaslis** [comment]
👌🏼 thanks, that works for me.
