### ISSUE TITLE
String format for radicle::cob::op::OpId

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#245]
A heartwood `Comment` uses the OpId type to uniquely identify it, and it may be used in other places.  This ID type needs a string format to allow referencing it to users.  For example, replying to a comment via command line argument.

How should the be formatted and parsed?

```
/// Identifies an [`Op`] internally and within the change graph.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct OpId(Lamport, ActorId);
```

**Comment by cloudhead** [comment]
I was thinking we could do `<actor-id> "/" <lamport>`, so for example `z6MksFqXN3Yhqk8pTJdUGLwATkRfQvwZXPqR2qMEhbS9wzpT/12`

**Comment by slack-coder** [comment]
> I was thinking we could do `<actor-id> "/" <lamport>`, so for example `z6MksFqXN3Yhqk8pTJdUGLwATkRfQvwZXPqR2qMEhbS9wzpT/12`

:+1:  implemented so we have something to work with.  Lets keep this issue open until we settle on this format or decide on another.
