### ISSUE TITLE
Confusion with two similar commands `rad auth` and `rad-auth`

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#261]
When installing all the project packages, a `rad-auth` command is installed alongside `rad` which has the `rad auth` subcommand.  Using `rad-auth` results in the radicle-node failing to start.

```
rm -fr $RAD_HOME/*
rad-auth
# id: z6MkvBDVj8nmpNQfa8dAWMSfcPcTMkxVw6AuPruXrnHK3Zrh
# home: /srv/heartwood/var/rad
./bin/radicle-node --listen=$NODE_LISTEN_ADDR
2023-02-01T09:01:12.966-05:00 ERROR node     Fatal: ssh keygen: cryptographic error
```

**Comment by xphoniex** [comment]
That doesn't sound right. Are you sure it's not leftover from [radicle-dev/radicle-cli](https://github.com/radicle-dev/radicle-cli)?

**Comment by slack-coder** [comment]
Yes

```
export CARGO_INSTALL_ROOT=$(pwd)

git clone https://github.com/radicle-dev/heartwood
(cd heartwood;
  cargo install \
      --force \
      --locked \
      --path radicle-cli \

  cargo install \
      --force \
      --locked \
      --path radicle-remote-helper \

  cargo install \
      --force \
      --locked \
      --path radicle-tools \

  cargo install \
      --force \
      --locked \
      --path radicle-node \
)
ls -l $CARGO_INSTALL_ROOT/bin
```

**Comment by slack-coder** [comment]
Its coming from the `radicle-tools` crate.  @cloudhead perhaps we could trim this out? It looks to be a duplicate.

**Comment by slack-coder** [comment]
I was making the mistake of building and installing the radicle-tools package.  Its the source of the extra `rad-auth` command.
