### ISSUE TITLE
Node control

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#271]
We need some kind of way of interacting with the node:
* [x] Checking the node status (`rad node status`)
* [x] Starting the node (`rad node start`)
* [x] Stopping the node (`rad node stop`)
* [x] ~~Connecting to the node's control socket (`rad node connect`)~~
* [x] Printing out our routing table (`rad node routing`)
* [x] Printing out our tracking policies (`rad node tracking`)

**Comment by FintanH** [comment]
Taking some notes and questions here while I explore this.

I'm trying to figure out how the state of the node is determined. From what I can see, a `Node` is just a wrapper around a UNIX socket. There's currently no "start" functionality, so is the `Node` started once we call the `new` constructor? Would that mean to `stop` the `Node`, we would first need to check the socket path exists and then construct the `Node` to call `shutdown`? 

Also looking at `routing` and `tracking`, it seems like there's no functionality at the service level (i.e. `service::Command` has no variant for this) that exists for getting that information yet. This would require wiring up two commands for getting the entries and serving them up, also adding functions to the `Handle` trait. Would that be correct?

**Comment by FintanH** [comment]
Why is `Node` defined in `radicle::node` in the first place? It seems like the dependent are `radicle-cli`, `radicle-tools`, and `radicle-remote-helper`, without any internal use. `radicle-cli` already depends on `radicle-node` I believe, remote helper could depend on `radicle-node`, and the latter is not needed afaik. So would it make sense to move this `Handle` and `Node` stuff into `radicle-node` itself?

**Comment by cloudhead** [comment]
> So would it make sense to move this `Handle` and `Node` stuff into `radicle-node` itself?

This would require `radicle-cli` to depend on `radicle-node`, which doesn't really make sense imo. It should only depend on the node "interface", not the node itself.
