### ISSUE TITLE
Node systemd unit files

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#272]
A unit file for the node, for systemd-compatible OSes.

**Comment by slack-coder** [comment]
@cloudhead can I grab this one?

**Comment by cloudhead** [comment]
Yup!

**Comment by slack-coder** [comment]
@gsaslis do you have a systemd service file setup?  I noticed you have the docker compose system setup in a PR.

I've created one, just needs testing, and I left if on the back burner for a while now.

**Comment by gsaslis** [comment]
@slack-coder I don't, I'm afraid... :/

**Comment by slack-coder** [comment]
Here's a start at https://github.com/radicle-dev/heartwood/pull/489.  Its documented to help users configure to their system or context.

One of the problems is radicle-node needs interfacing with the user to decode its secret key.  The workaround is to define RAD_PASSPHRASE in the systemd file, but its not ideal.

It still needs testing.

**Comment by slack-coder** [comment]
@cloudhead this should be done

**Comment by cloudhead** [comment]
Closed by #489
