### ISSUE TITLE
Routing table pruning

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#29]
Currently, entries are only ever *added* to the routing table.

We should keep track of when the entries were added, and periodically prune the table of old entries. Likewise, when an existing entry is received again, its timestamp should be updated, to keep it from being evicted.

**Comment by slack-coder** [comment]
Fortunately tracking project information is a little more straightforward.  Inventory Announcements contain an entire listing of a node's projects, making it more about a node's status.  i.e. Is the node  dead?  Can we query it directly?

In the mean time I'll push ahead with a pruning time for up to a week.  It's arbitrary, but a longer time is better for badly connected network.

**Comment by cloudhead** [comment]
Closed by #89
