### ISSUE TITLE
Tor support via Socks5 proxy

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#30]
To allow for NAT traversal and to provide anonymity to those who need that, we should have support for Tor connectivity and `.onion` addresses.

The way to do this is to support connecting via SOCKS5. This will also enable I2P and Nym support in the future.

**Comment by adaszko** [comment]
Hi, is this being worked on?  I’d be interested in helping

**Comment by adaszko** [comment]
It might worth checking Arti, a Rust rewrite of Tor: https://blog.torproject.org/arti_100_released/

```
You can test Arti as a SOCKS proxy (if you're willing to compile from source) and as an embeddable library (if you don't mind a little API instability).
```

**Comment by dr-orlovsky** [comment]
At this moment we already done it in the most simple way: via SOCKS5 proxy without use of control port. We also ended up with doing minimalistic no-ext-deps implementations for both [Onion addresses](https://github.com/Cyphernet-WG/rust-cyphernet/blob/noise-refactor/addr/src/tor.rs) and [SOCSK5 client](https://github.com/Cyphernet-WG/rust-cyphernet/tree/noise-refactor/socks5-client).

For the future what is missing is:
- SOCKS55 authentication
- Tor control protocol

**Comment by dr-orlovsky** [comment]
Thanks for info about Arti!

Had a look at it, and while I think the project is great, there are at least two things which makes it harder to adopt it here:
- It uses Tokio and async at the very core (it has plenty of dependencies and long compile time and we do not need async in Radicle)
- There is no tiny Onion address crate which we can use when we do not need to run Tor server

**Comment by cloudhead** [comment]
This is implemented.
