### ISSUE TITLE
Git is exposing itself

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#319]
Heartwood exposes git through its own port, and should minimize exposure to the git daemon supporting it.  It should be started listen on a random high port (on localhost), however it is being exposed on git's official port.

**Comment by cloudhead** [comment]
What's the actual issue though? What does "and should minimize exposure to the git daemon supporting it" mean?

**Comment by cloudhead** [comment]
Yeah, I agree, but not sure this is our business. git-daemon doesn't support unix socket files, so we're forced to open a port. A high port isn't necessarily safer than the default port, and it could be taken as well, so we'd have to add logic there. It's the job of the operator to setup the appropriate firewall I would think.

**Comment by slack-coder** [comment]
What about binding it to the localhost (127.0.0.1) by default?

**Comment by cloudhead** [comment]
Yeah, we can definitely do that, good idea.
