### ISSUE TITLE
Weird `500` error on httpd

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#332]
Try hitting this route: https://seed.radicle.xyz/aa/a

You'll get a 500. We should always return 404 if the route isn't valid.

**Comment by FintanH** [comment]
Ah, I posted on the PR for this but... why `404` and not [`400`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)? I would think it's a 400 because the client made a bad request using an incorrect route.
