### ISSUE TITLE
Document `/mnt/radicle/heartwood` in docker-compose.yml

### ISSUE THREAD

**Issue by gsaslis** [radicle-dev/heartwood#337]
I tried cloning the repo and running `docker-compose up` and the images built correctly, but when they actually started I got an error message because `/mnt/radicle/heartwood` didn't exist on my machine. 

I tried replacing that with an empty folder, but: 

* radicle-node fails with: 
```
radicle-node     | 2023-02-19T11:44:21.387Z ERROR node     Fatal: key not found in '/root/.radicle/keys'
```

* and radicle-httpd fails with: 
```
radicle-httpd    | 2023-02-19T11:44:21.353758Z ERROR radicle_httpd: Fatal: no profile found at the filepath '/root/.radicle'
```

I guess there are some files I am missing in that path ? Do I need to run anything in particular to initialise that folder **before** running `docker-compose up` ?

**Comment by gsaslis** [comment]
I was able to work around this by first running `rad auth` (with the latest pre-built binary) and then pointing the mount point to `~/.radicle` (`/Users/$USER/.radicle` on macOS)

**Comment by gsaslis** [comment]
(but the issue about documenting that path still remains, I think)

**Comment by cloudhead** [comment]
@adaszko wdyt?

**Comment by adaszko** [comment]
Oh, it most definitely should be a changed to a different directory in your running it on your machine.  The /mnt directory was meant for server use and is specific to our infra.  I think a comment recommending editing this path should suffice

**Comment by cloudhead** [comment]
Yeah, we don't really want users running via docker locally I think.

**Comment by gsaslis** [comment]
Yes, what wasn't clear was what is expected to be contained in that directory. 

From that point onwards, it sounds like more of a user choice how they run the node (and there's a point to be made that if the Radicle team deploys theirs via docker, that's a good place to start... ;) )

**Comment by adaszko** [comment]
If we could somehow embed the git binary inside of radicle-node and radicle-httpd, we’d be on a way to ship just a single self-contained binary which I think would be as simple as it gets.  Is such a thing even feasible? I.e. could we use libgit in places where we currently use the git executable?

**Comment by cloudhead** [comment]
> If we could somehow embed the git binary inside of radicle-node and radicle-httpd, we’d be on a way to ship just a single self-contained binary which I think would be as simple as it gets. Is such a thing even feasible? I.e. could we use libgit in places where we currently use the git executable?

I wish...

Currently, libgit trails a few years behind git, in terms of functionality. Unfortunately the two projects (libgit2 and git) are not developed by the same people.

**Comment by gsaslis** [comment]
@adaszko / @cloudhead would love your 👀 on #452
