### ISSUE TITLE
Queue worker fetch requests when necessary

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#342]
Currently if a node is being fetched from, and we try to fetch from it again, we log an error. We should ideally handle that more gracefully by queuing the request and retrying, or by finding another node.

**Comment by keepsimple1** [comment]
Is there anyone working on this? If not, I will take a look.

**Comment by keepsimple1** [comment]
> We should ideally handle that more gracefully by queuing the request and retrying, or by finding another node.

Can we use [`Reactor.outbox`](https://github.com/radicle-dev/heartwood/blob/05d2487a47afba3bf2ab3aabd13d74ddf2f8bcd8/radicle-node/src/service/reactor.rs#L47-L50) to queue the request? Is there a gotcha for that?

**Comment by cloudhead** [comment]
Yeah, that's what I'm thinking. It wasn't made for this use-case, but it may just work!

**Comment by cloudhead** [comment]
Closed by #401
