### ISSUE TITLE
Consolidate mentions of "id" in CLI

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#369]
In the CLI help text, ensure old names eg. `--id`, `--peer`, `<peer>` etc. are updated according to:
* All mentions of Repository IDs use `<rid>` for values in help text, `--repo` for options, and `RID` in help/error messages.
* All mentions of Node IDs use `<nid>` for values in help text, `--node` for options and `NID` in help/error messages.
* All mentions of DIDs use `<did>` for values in help text, and `DID` in help/error messages. Leave options as-is.

**Comment by xphoniex** [comment]
do we also want to standardize issues/patches/etc under `oid` or is `id` good enough?

**Comment by cloudhead** [comment]
I think `<issue>` is not bad, but maybe `<issue-id>` is even better, clearer.
