### ISSUE TITLE
Figure out story around `radicle_git_ext::NotFound` and Git errors

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#38]
We're currently using this `NotFound` type which is supposed to be private. Figure out how we should handle cases where eg. a reference target is `None`, and what error we should return, without depending on that type.

> Ok, the thing is it would be nice to have a "good" git error type, which git_ext::Error is pretty close to, or have maybe a RepositoryExt trait that is more flexible. The ref.target() case is a good example of this: most of the time you want the oid of a reference, and this involves repo.find_reference(...)?.target().ok_or(...)? which is cumbersome.
> So I use my own methods for getting references, which returns a git_ext::Error, but this requires access to NotFound, so that I can return a "not found" error when the target is missing. Without this, I'd have to create yet another git error type..

**Comment by FintanH** [comment]
Ok, right you brought this up when I was writing `git-storage`. I proposed that we have top-level functions that can be fallible and not return `Option`.

Did you have any plans for using `git-storage`?

**Comment by cloudhead** [comment]
That sounds good. If we have a `is_not_found()` method on the error then it can be used to treat not found errors differently when needed.

I've started to remove `Result<Option<T>, E>` in favor of `Result<T, E>` for all low-level functionality, eg. storage-level in heartwood. I think result-wrapped options make sense, but only perhaps for high-level apis..

> Did you have any plans for using git-storage?
Is this question related to the issue? If not, I think I commented on this in some issue in radicle-git if I remember..

**Comment by FintanH** [comment]
Hmmm, I wonder if we could add something to https://github.com/radicle-dev/radicle-git/blob/main/radicle-std-ext/src/result.rs like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e318c43cb00069efca0e95805fbfb88f).

```rust
pub trait NotFound<T, E> {
    fn is_not_found<E2, F>(self, f: F) -> Result<T, E2>
    where
        E2: From<E>,
        F: FnOnce() -> Result<T, E2>;
}

impl<T, E> NotFound<T, E> for Result<Option<T>, E> {
    fn is_not_found<E2, F>(self, f: F) -> Result<T, E2>
    where
        E2: From<E>,
        F: FnOnce() -> Result<T, E2>,
    {
        match self {
            Ok(None) => f(),
            Ok(Some(t)) => Ok(t),
            Err(e) => Err(e.into()),
        }
    }
}

#[derive(Debug)]
pub enum Error {
    NotFound,
    Other
}

fn main() {
    let missing = Ok::<Option<String>, Error>(None);
    let missing = missing.is_not_found(|| Err(Error::NotFound));
    println!("{:?}", missing);
    
    let found = Ok(Some("hello".to_owned()));
    let found = found.is_not_found(|| Err(Error::NotFound));
    println!("{:?}", found);
    
    let err = Err::<Option<String>, _>(Error::Other);
    let err = err.is_not_found(|| Err(Error::NotFound));
    println!("{:?}", err);
}
```

> > Did you have any plans for using git-storage?
> 
> Is this question related to the issue? If not, I think I commented on this in some issue in radicle-git if I remember..

Ya, so the conversation briefly happened [here](https://github.com/radicle-dev/radicle-git/pull/17#pullrequestreview-1119018315). I didn't end up following through but could do in a follow-up. Why I'm asking here though is because you want to avoid the `Option` like functions and one route could be going through `git-storage` but I'm not sure what your plans are for using it :) I assumed you would be interested in using it but :shrug:

**Comment by cloudhead** [comment]
@FintanH should we close this? I don't know what the status is anymore.

**Comment by FintanH** [comment]
Ya, I'd say we close it. It seems like the `radicle` code is using `is_not_found` methods everywhere it needs to
