### ISSUE TITLE
Using Force for Fetch Refspecs

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/heartwood#397]
The `Namespaces` type provides refspecs for the fetching. At the moment, these refspecs do not use `+` for forcing non-fast-forwards. 

On one hand, we would like to use fast-forwards when a peer has force-pushed changes to their reference set, otherwise, these would currently be rejected.

On the other hand, for example, if we wanted Eve's changes and we fetched them from Alice and Bob, where Alice has the most up-to-date state and Bob is behind, then we will end up in a behind state if we fetch from Bob after Alice. Unless... Would we reject the fetch from Bob because the signed refs are not a fast-forward?

So rubberducking as I write this... The invariant is that signed refs _always_ need to be a fast-forward, which we should fetch and verify first, and then all references in that set are force fetched because we know it's safe. In the case above, we reject the fetch from Bob because we know the signed refs are ahead -- we just fetched the latest from Alice.

**Comment by cloudhead** [comment]
:bulb: !

**Comment by FintanH** [comment]
In order for this to work correctly we need to split the fetching from a node into two stages:
1. Fetch the `rad` references -- these are needed to determine the validity of the identities and the signed refs.
2. For each remote we are fetching from, fetch the valid signed refs using the forced (`+`) refspec.

Something to be aware of is that step 1. can fail verification, for example, if a malicious actor is trying to fake signed refs. We don't want to overwrite the existing references so we need to have some kind of staging process. In the prior art, i.e. `link-replication`, these references were fetched into an in-memory refdb for verification purposes. However, this requires being able to tap into a custom protocol. For our case, it should be enough to fetch into a `staging` area, e.g. `refs/namespaces/staging`. If any of those references fail to verify then they can be pruned.

For each staged set of signed refs, we can ensure that they are a fast-forward of our currently seen signed refs, if they are not they can be discarded as they are out of date. If they are a fast-forward we can move forward the real signed refs reference and for each reference in its payload create a forced refspec. We send those refspecs off for fetching, completing phase 2, and the whole fetch process.

**Comment by cloudhead** [comment]
Related: #14
