### ISSUE TITLE
Port `cob` from radice-link

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/heartwood#4]
Port over the `cob` crate[[0]] from `radicle-link`.

Some challenges for this will be:
* Untangling `link-crypto` dependency
* Untangling `link-identities` dependency 
* Using `radicle-git` over the `radicle-link` repos (including using `git-storage`) 

[0]: https://github.com/radicle-dev/radicle-link/tree/master/cob

**Comment by cloudhead** [comment]
Yeah. Note that we're currently using our own (non-monorepo) storage implementation.

**Comment by cloudhead** [comment]
Closed in #93 #60
