### ISSUE TITLE
Improve `rad patch` target selection

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#400]
When creating a new patch via `rad open`, it needs to know the target repository (or peer) and branch.  The branch is hard coded as the project's default branch (e.g. master).  The target therefor is defined by the peer (or repository).

The current implementation only works when one target is available, otherwise it fails with error (resulting in issue #380).

I propose setting the target by default to the delegate's master branch.  Radicle currently supports the case of only one delegate anyways.  In the uncommon case the user wants to patch against another peer's branch, he/she can do so via an optional argument.

**Comment by slack-coder** [comment]
There was confusion about Patches and merge Targets.  Instead of the patch requiring a (target repository, branch) pair, it requires a target git reference only.

Currently in Rad there is one sane git reference to use, the quorum of the delegates master branch.

**Comment by cloudhead** [comment]
Closed by #407
