### ISSUE TITLE
Have command to setup git remote for tracked peers

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#432]
We want to have a `rad remote` version for `git remote` which uses Radicle's did's and aliases to make it easier to operate with remotes on the radicle network.  These will operate on a per-project basis.

From the set of `git` commands, we have:
```
       git remote [-v | --verbose]
       git remote add [-t <branch>] [-m <master>] [-f] [--[no-]tags] [--mirror=(fetch|push)] <name> <URL>
       git remote remove <name>
```

We want a trimmed down version for rad:

- rad remote [-v | --verbose]
- rad remote add <did|peer alias> [--alias <alias>]
  The alias argument overwrite's `git remote`s name
- git remote remove <did|peer alias>

Note: updated by @slack-coder

**Comment by cloudhead** [comment]
@vincenzopalazzo will be working on this :+1:

**Comment by slack-coder** [comment]
@cloudhead @vincenzopalazzo how is the issue description for what we want?

**Comment by cloudhead** [comment]
Imported
