### ISSUE TITLE
Example's should handle '$' in command output

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#439]
The examples in radicle-cli contain sequences of commands with their corresponding output.  The commands are tested against their output to prove accuracy of the documentation and command correctness.

The command sequences begin with '$', which causes problems for commands with lines beginning with '$' as an output.

For example `rad merge`.  The `rad merge` command is given a the top of the block, and outputs the line '$ git merge'.  The test mistakes `rad merge` as having one line of output, and believing `git merge` is the next command to run.

```
$ rad merge a07ef7743a32a2e902672ea3526d1db6ee08108a
Merging a07ef7743a3 R2 (f5648be) by did:key:z6Mkt67GdsW7715MEfRuP4pSZxJRJh6kj6Y48WRqVv4N1tRk into master (f2de534) via fast-forward...
$ git merge --ff-only f5648be791a0b2abe2c6ac2a50dd832a411f7c2f
Updating f2de534..f5648be
Fast-forward
 README.md       | 0
 REQUIREMENTS.md | 0
 2 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
 create mode 100644 REQUIREMENTS.md
✓ Updated master f2de534 -> f5648be via fast-forward
✓ Patch state updated, use `rad push` to publish
```

From https://github.com/slack-coder/heartwood/blob/slack-coder/documentation-test-merge/radicle-cli/examples/workflow/5-patching.md

**Comment by cloudhead** [comment]
:laughing:

**Comment by cloudhead** [comment]
I think we could change the output, because without the coloring, it's very confusing if someone has `$` as their prompt, and also for the docs it's confusing.

**Comment by cloudhead** [comment]
Code is here: https://github.com/radicle-dev/heartwood/blob/70779ec14870222af11ff1dbb075ece63d558450/radicle-term/src/io.rs#L126-L128

We should change it to:

```rust
    println!("{} `{}`..", style("Running").dim(), style(msg).dim());
```

**Comment by slack-coder** [comment]
Thanks, I was looking in the wrong place.
