### ISSUE TITLE
Figure out network bootstrapping

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#455]
Currently, when the node starts up, it doesn't have an address book and doesn't know who to connect to.
We should have a list of bootstrap nodes that ship with the client software, eg. seed.radicle.xyz, to allow the node to find peers initially.
Later, as the network grows, we could use other mechanisms to bootstrap nodes.

> Fintan: This reminded me of setting up Arch Linux, where there's a list of common mirrors that you would want to connect to. I wonder if there could be a rad setup that could encapsulate many of these wizard-like configurations and run the auth for the first time.
> And also a wiki of some sorts for showing those common mirrors would be cool :)

**Comment by FintanH** [comment]
This reminded me of setting up Arch Linux, where there's a list of common mirrors that you would want to connect to. I wonder if there could be a `rad setup` that could encapsulate many of these wizard-like configurations and run the auth for the first time. 

And also a wiki of some sorts for showing those common mirrors would be cool :)

**Comment by cloudhead** [comment]
Yeah those are good ideas :)

**Comment by cloudhead** [comment]
Imported
