### ISSUE TITLE
Elaborate on breaking documentation tests

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#457]
Could we elaborate on breaking example tests?  It would save developer time having to find where the breaking issue comes from.

For example, if we cause a break in our example tests by making the following change:

```
diff --git a/radicle-cli/examples/workflow/2-cloning.md b/radicle-cli/examples/workflow/2-cloning.md
index e34b57c..64c0185 100644
--- a/radicle-cli/examples/workflow/2-cloning.md
+++ b/radicle-cli/examples/workflow/2-cloning.md
@@ -28,7 +28,7 @@ Hello World!
 Let's check that the remote tracking branch was setup correctly:

   ```
  -$ git branch --remotes
  +$ git branch
     rad/master
     z6MknSLrJoTcukLrE435hVNQT4JUhbvWLX4kUzqkEStBU8Vi/master
   ```
```

The test breaks with an uninformative error.

```
test rad_workflow ... FAILED

failures:

---- rad_workflow stdout ----
thread 'rad_workflow' panicked at '
--- Expected
++++ actual:   stdout
   1      -   rad/master
   2      -   z6MknSLrJoTcukLrE435hVNQT4JUhbvWLX4kUzqkEStBU8Vi/master
        1 + * master

```

Having the name of the example file and the command causing the break would help developers and hackers on the code.

**Comment by cloudhead** [comment]
The name is included in the logs :)

**Comment by slack-coder** [comment]
> The name is included in the logs :)

Good to know.  `logger::init(log::level::Debug)` at the head of the test?

**Comment by cloudhead** [comment]
Yeah, we use a library for the assertion/diff, so it looks like we can't change the error message. Hence the log.
