### ISSUE TITLE
Auto-generate documentation test output

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#458]
The documentation tests are great.  However updating the test's or the code can result in significant manual work.  The example tests stack on top of each other.  Having an effectual change on a single example tests can ripple onto the others.  The examples then have to be updated manually.

Can we auto-generate the example test command output.  Following on from issue #457, it could rewrite

```
$ git branch
rad/master
z6MknSLrJoTcukLrE435hVNQT4JUhbvWLX4kUzqkEStBU8Vi/master
```

to

```
$ git branch
* master
```

**Comment by slack-coder** [comment]
Maybe better with a medium priority?  Correcting the examples can become what feels like a 15 minute+ time suck.

**Comment by cloudhead** [comment]
The time investment to get this working is significant though..
