### ISSUE TITLE
Fork off example workflow when elaborating on commands

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#459]
The workflow examples is an ordered set of examples guiding the user on how to use `radicle` with a theme. Other examples exist in the `radicle-cli/examples" directory which operate outside the workflow documenting specific commands more.  For example "radicle-cli/examples/rad-issue.md".  There are others which are not mentioned in the workflow at all ("radicle-cli/examples/rad-node.md").

The problem is there is redundancy between the workflow and the examples in "radicle-cli/examples" (radicle-cli/examples/rad-issue.md and radicle-cli/examples/workflow/3-issues.md).

'rad-issue.md' is stacked on "examples/rad-init.md", instead what about stacking it on top of 'workflow/1-*' to "workflow/3-issues.md".  It would remove redundancy and use a single context, instead of having one for the example and another for the workflow.

**Comment by cloudhead** [comment]
Hmm I'm not sure the redundancy is a problem though? Each doc file is able to test a bunch of things that perhaps we don't want in the workflow.

**Comment by slack-coder** [comment]
> Each doc file is able to test a bunch of things that perhaps we don't want in the workflow.

We can handle these cases by forking off from the workflow.  So instead of:

 - rad-init.md
 - rad-issue.md
 - rad-patch.md

We fork off:

 - workflow/1-new-project.md
 - ...
 - workflow/4-patching-contributor.md
 - rad-patch.md

It provides a single list of examples instead of two or more lists of examples.  We also remove redundancy where we don't need it, e.g. rad-init.md.
