### ISSUE TITLE
Support dropping into shell from examples

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#460]
Could we enable dropping into the shell from an example.

The user could change "workflow/3-issues.md" to

```
diff --git a/radicle-cli/examples/workflow/3-issues.md b/radicle-cli/examples/workflow/3-issues.md
index 63a664f..71ac2cf 100644
--- a/radicle-cli/examples/workflow/3-issues.md
+++ b/radicle-cli/examples/workflow/3-issues.md
@@ -18,6 +18,7 @@ The issue is now listed under our project.
 \```
 $ rad issue list
 b05e945bb63c11bf80320f4e26ad1d1f7c51f755 "flux capacitor under powered"
+$ sh
 \```
```

And he could drop into a shell afer `rad issue list` and explore using 'rad' from the context.  It will help new users learn radicle, and it will help developers explore bugs.

**Comment by cloudhead** [comment]
Why would a user be running the doc tests?

**Comment by slack-coder** [comment]
Are the examples documentation for users as well as tests?  The entry point could be provided as a script or some other means.

**Comment by cloudhead** [comment]
Yeah, I mean I don't think users would directly browse them through the repo though. I also don't think most users will have a rust toolchain installed to be able to run the tests.

**Comment by cloudhead** [comment]
I'm going to close this, as there's no clear use-case for users.
