### ISSUE TITLE
Fetch trusted nodes on clone

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/heartwood#494]
In https://github.com/radicle-dev/heartwood/pull/476/files#diff-055d858199081872874d6d4adddbcd75e7cd01a9359eaf86d1faf0c9eb437ac2R276-R285, I noticed that our cloning logic was expecting to also fetch any trusted nodes -- the changes in the PR only allow for fetching the delegates during a clone.

This works but it would be beneficial to fetch any remotes that we know about in our tracking. One way to go about this is to modify `Namespaces` to look something like:
```rust
#[derive(Default, Debug, Clone, PartialEq, Eq)]
pub enum Namespaces {
    /// All namespaces.
    #[default]
    All,
    /// A single namespace, by public key.
    One(PublicKey),
    /// Many namespaces, by public keys.
    Many {
        trusted: Vec<PublicKey>,
        delegates: Option<NonEmpty<PublicKey>>,
    },
}
```

This would allow us to create the `Many` variant in `namespaces_for` using `node_policies` and then optionally load `delegates` if the `repository` exists.

**Comment by FintanH** [comment]
> Hmm but why distinguish between trusted and delegates?

Good question. Perhaps this is just expressed in terms of `BTreeSet` or `HashSet` of the `PublicKey`s. I'd need to play around in #476 to see what that entails.

**Comment by cloudhead** [comment]
Can this be closed?

**Comment by FintanH** [comment]
Aye, it sure can!
