### ISSUE TITLE
Threading clocks for updating actions

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/heartwood#496]
It came to our attention in the Zulip topic, ["patch review modification"](https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/patch.20review.20modification), that using `LWWReg::from` was giving subsequent actions the same clock value as their predecessors. This resulted in a `Reject` not being able to turn into an `Accept` on a second review of a patch.

The solution is to use the `clock` value that was produced for the `Op` and pass that into `new`, avoiding the call to `from`. There could be other potential areas where this is an issue in our cobs.

I would recommend that we remove the `From` impls in favour of always using `new`. This saves us from potentially using these things wrong in the future and `Clock::default()` is not hard to type :)

**Comment by FintanH** [comment]
Looking into this and ran into a fun bit of semantics :)

So we have the following:
```rust
pub struct Review {
    /// Review verdict.
    pub verdict: LWWReg<Option<Verdict>>,
    /// Review general comment.
    pub comment: LWWReg<Option<Max<String>>>,
    /// Review inline code comments.
    pub inline: LWWSet<Max<CodeComment>>,
    /// Review timestamp.
    pub timestamp: Max<Timestamp>,
}
```

And also this:
```rust
pub enum Action {
    /* variants */
    Review {
        revision: RevisionId,
        comment: Option<String>,
        verdict: Option<Verdict>,
        inline: Vec<CodeComment>,
    },
    /* more */
```

Now, if a `Review` only wants to update the `Verdict`, setting the `comment` to `None`, then the latest `Review` gets set to `None` because of the `merge` semantics for the `LWWReg`. The `apply` sees there's a new `clock` for that `Review` passing it to `LWWReg` and it `set`s it to `None`.

**Comment by sebastinez** [comment]
Yeah also found out about this, but I thought that we can handle this in the web client or the CLI.
It sounds to me that, if you remove your verdict eventually also means what you wrote doesn't apply anymore?

**Comment by FintanH** [comment]
> Yeah also found out about this, but I thought that we can handle this in the web client or the CLI.

I don't find it appealing to "keep in mind" that you need to use the old value if there is one. The better approach would be to try to find a better CRDT for updates -- not sure what yet though.

>  It sounds to me that, if you remove your verdict eventually also means what you wrote doesn't apply anymore?

Sorry, what do you mean?

**Comment by sebastinez** [comment]
> Sorry, what do you mean?

What I meant is that the comment is bound to the verdict, and a old comment isn't in line any more with the new verdict.
But I'm not opposed to find better CRDTs.

**Comment by FintanH** [comment]
> What I meant is that the comment is bound to the verdict, and a old comment isn't in line any more with the new verdict.

That's not necessarily true. If we're modelling it after GitHub then it would be the case but it's not expressed like that in the code. Otherwise, it would have to be something like this:
```rust
pub enum Verdict {
  Accept { comment: Max<String> },
  Reject { comment: Max<String> },
}

pub struct Review {
    pub verdict: LWWReg<Option<Verdict>>,
    pub inline: LWWSet<Max<CodeComment>>,
    pub timestamp: Max<Timestamp>,
}
```

Maybe that is something we'd prefer?

However, we still end up in the same boat when we want to update the `inline` comments and not the `verdict`

**Comment by cloudhead** [comment]
Hmm you're talking about `Redactable`. `Option` works differently.

**Comment by FintanH** [comment]
Ugh, `master` changed under my buttocks...

If we look at the commit @sebastinez made, the [comment](https://github.com/radicle-dev/heartwood/commit/fa15ca59f18ad6c4714cd47b592e0d0f6628cdbc#diff-7ae799f0e448febfbcb3706da8085a0b54aa873bc70586866f1cc5932a5250caL1376) and the [verdict](https://github.com/radicle-dev/heartwood/commit/fa15ca59f18ad6c4714cd47b592e0d0f6628cdbc#diff-7ae799f0e448febfbcb3706da8085a0b54aa873bc70586866f1cc5932a5250caL1383) were expected to be carried through the `review` and we were getting away with it because of the clock logic.

I've shown the actual intent of how `review` is supposed to be used in [this PR](https://github.com/radicle-dev/heartwood/pull/498/files#diff-7ae799f0e448febfbcb3706da8085a0b54aa873bc70586866f1cc5932a5250caR1440-R1457)
