### ISSUE TITLE
Announce refs on startup

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#51]
It's likely that we will need a mechanism to announce local refs on startup. For example, if a user's node is not running, and they push to storage, those refs are not announced.

**Implementation**
Iterate through all projects, filter projects that have signed refs by the local user (ie. we have a local fork), and announce projects whos refs were updated since the last node refs announcement. This means we need to keep track of the last refs announcement somewhere.

Alternatively, as a first pass, we can simply announce all refs of projects that have been forked locally.

**Comment by cloudhead** [comment]
The idea of a `fetched_by` column is interesting for sure. I think I would think of it more as just `announced_by` though, and we can updated it simply when we receive any RefAnnouncement.

**Comment by FintanH** [comment]
> The idea of a `fetched_by` column is interesting for sure. I think I would think of it more as just `announced_by` though, and we can updated it simply when we receive any RefAnnouncement.

Ah because a `RefAnnouncement` entails that the node replicated the data?

**Comment by cloudhead** [comment]
If the announcement message itself is signed by a node, it means that node has the refs, ie. it's always an announcement of locally available refs. If it's been relayed, it doesn't say anything about the relayer. Does that make sense?

**Comment by cloudhead** [comment]
Eg. if Bob just fetched Eve's refs, Bob will gossip `RefAnn([/eve/main, eve-sigrefs], bob-signature])` to Seed, and Seed will relay that to Alice. Alice gets it from Seed, buit notices that Bob signed the announcement, so Bob has Eve's refs.

**Comment by FintanH** [comment]
Ok, that makes sense :+1: Thanks for the clarification :)

**Comment by cloudhead** [comment]
Imported
