### ISSUE TITLE
Associated Error in Signer

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/heartwood#78]
Would we not mark these ones as `Infallible`?
```suggestion
    fn try_sign(&self, msg: &[u8]) -> Result<Signature, Infallible> {
```

_Originally posted by @FintanH in https://github.com/radicle-dev/heartwood/pull/74#discussion_r1012716921_

**Comment by FintanH** [comment]
Ah yes, this quickly becomes a pain in the ass because you also want to `Box` the error when you pass around `Box<dyn Signer>` and the errors won't match for different objects, for example, `MemorySigner` vs `AgentSigner`.

**Comment by cloudhead** [comment]
:joy:
